### ISSUE TITLE
Why there will use the blob when do the ingest using IngestFromStreamAsync, the connection string to blob is leaked during this process

### ISSUE THREAD

**Issue by zhunipingan** [Azure/azure-kusto-samples-dotnet#30]
I want to use the var ingestClient = KustoIngestFactory.CreateDirectIngestClient(kcsb); var ingestionProperties = new KustoIngestionProperties(databaseName, tableName) { Format = DataSourceFormat.multijson }; await ingestClient.IngestFromStreamAsync(stream, ingestionProperties);

But I found in this process, ther will be a put operation to blob storage, which contains the SAS token, https://xxxxxxxxxxxxxxxxxxxxxxxxx.blob.core.windows.net/xxxxxxxxxxxxxxxxxx-temp-xxxxxxxxxxx/3066_Upload_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.multijson.gz?sv=2022-11-02&st=2024-03-20T23%3A10%3A01Z&se=2024-03-21T23%3A15%3A01Z&sr=c&sp=rwd&sig=xxxxxxxxxxxxxxxxxxw%3D, Will this leak the information of the connected blob, which poses a security risk. I was reported this problem in the code while using it

Thanks！

**Comment by AsafMah** [comment]
We answered you in the nuget email, next time please choose only one channel for communication, unless you see a long time without a response.
