### ISSUE TITLE
Where can I file an issue for the dotnet SDK?

### ISSUE THREAD

**Issue by dg-eparizzi** [Azure/azure-kusto-samples-dotnet#6]
I've been looking everywhere and I cannot find the Github repo for [Microsoft.Azure.Kusto.Data](https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data/). I'm guessing is not open source?

If not, where can I report a bug?

**Comment by yogilad** [comment]
https://github.com/Azure/azure-kusto-dotnet/issues
